apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: m2glisi
spec:
  selector:
    app: mysql
  ports:
  - protocol: TCP
    port: 3306  # Port du Service (utilisé par l'app Spring pour se connecter à MySQL)
    targetPort: 3306  # Port du conteneur MySQL (doit correspondre au containerPort)
  type: ClusterIP  # Service accessible uniquement DANS le cluster
# kubectl create -f mysql-service.yaml
