apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: m2glisi
spec:
  selector:
    app: mysql
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
  type: ClusterIP
# kubectl create -f mysql-service.yaml
