apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
  namespace: m2glisi
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "root"
  MYSQL_DATABASE: "stockmanagement_db"
# kubectl create -f mysql-secrets.yaml
