apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-svc
  namespace: m2glisi
spec:
  selector:
    app: phpmyadmin
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30081
  type: NodePort
# kubectl create -f phpmyadmin-service.yaml
